import SideBar from './components/sidebar'

import { personal } from '../data/personalInfo';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <SideBar/>
        {children}
        </body>
    </html>
  )
}
